// Module included in the following assemblies:
//
// * installing/installing_helm/install-helm-quick.adoc

:_mod-docs-content-type: CONCEPT
[id="generate-init-bundle-helm-quick_{context}"]
= Authentication credentials for secured clusters

[role="_abstract"]
To secure communication between Central and the services running on a secured cluster, you must use authentication credentials during the installation of the secured cluster. {rh-rhacs-first} supports different methods for generating these credentials depending on your installation method and requirements.

You can generate the following authentication credentials by using the `roxctl` CLI:

Cluster registration secret (CRS):: A CRS is a specific type of secret that allows a new secured cluster to connect to Central. It contains data that authenticates the cluster and establishes a secure connection. A CRS includes metadata such as an expiration date and the ID of the creator. A CRS is the preferred way to set up a secured cluster.

Init bundles:: An init bundle contains the secrets required to authenticate a secured cluster with Central. The bundle includes certificates and keys that establish the trust relationship.

[IMPORTANT]
====
Both init bundles and CRS contain sensitive information. You must store them securely. If these credentials are compromised, an attacker could potentially add unauthorized clusters to your {product-title-short} environment.
====