// Module included in the following assemblies:
//
// * operating/evaluate-security-risks.adoc
:_mod-docs-content-type: PROCEDURE
[id="auto-lock-process-baselines_{context}"]
= Configuring auto-lock for process baselines

[role="_abstract"]
You can configure {product-title} ({product-title-short}) to automatically lock process baselines when they leave the observation period. You must enable auto-lock feature in both Central and in the secured cluster. 

Follow these guidelines when using auto-lock:

* The feature is enabled in Central by default and disabled in the secured clusters by default. Therefore, enabling the feature does not require restarting Central. However, changing the state of the feature in Central does require a restart of Central. 
* The feature is only enabled for process baselines for secured clusters where the feature is enabled.
* Disabling the feature after it has been enabled does not unlock process baselines that have been locked by the feature. 
* Enabling the feature does not lock process baselines that left the observation period before the feature was enabled.

.Procedure

. In the {ocp} web console, go to the {product-title-short} Operator page.
. In the top navigation menu, select *Secured Cluster*.
. Click the instance name, for example, *stackrox-secured-cluster-services*.
. Use one of the following methods to change the setting:
* In the *Form view*, under *Process baselines settings* -> *Auto Lock*, select *Enabled* or *Disabled*.
* Click *YAML* to open the YAML editor and locate the `spec.processBaselines.autoLock` attribute. Change to `Enabled` or `Disabled`.
. Click *Save.*
. To enable or disable the feature in Central, set the `ROX_AUTO_LOCK_PROCESS_BASELINES` environment variable. The default value is `true`.