// Module included in the following assemblies:
//
// * integration/integrate-with-image-registries.adoc
:_module-type: CONCEPT
[id="automatic-configuration-image-registry_{context}"]
= Automatic Configuration

[role="_abstract"]
{product-title} includes default integrations with standard registries, such as
Docker Hub and others.  In addition, it can also automatically configure
integrations based on artifacts found in the monitored clusters, such as image
pull secrets.  Usually, you do not need to configure registry integrations
manually.

For Amazon ECR integrations, {product-title} will automatically create ECR registry integrations if the following conditions are met:

* The cluster's cloud provider is AWS.
* The nodes in your cluster have an Instance IAM Role association and the Instance Metadata Service is available in the nodes.  For example, when using Amazon Elastic Kubernetes Service (EKS) to manage your cluster, this role is known as the EKS Node IAM role.
* The Instance IAM role has IAM policies granting access to the ECR registries from which you are deploying.

If the listed conditions are met, {product-title} monitors deployments that are pulling from ECR registries and autogenerates ECR integrations for them.

[IMPORTANT]
====
If you are using a GCR registry, {product-title} does not create a registry integration automatically.
====
