// Module included in the following assemblies:
//
// * operating/examine-images-for-vulnerabilities.adoc
:_mod-docs-content-type: PROCEDURE
[id="enabling-scanner-v4-helm-central_{context}"]
= Enabling RHACS Scanner V4 for Central when installing with Helm

[role="_abstract"]
Scanner V4 is not enabled by default, but you can enable it during installation.  Use this procedure to understand the steps you must follow when enabling Scanner V4. However, you might need to refer to the detailed installation documentation in "Additional resources", depending on the configuration of your other components.

.Procedure

. On the cluster where Central is installed, run the following command, using the instructions in "Install Central using Helm charts with customizations" if you need more information:
+
[source,terminal]
----
$ helm install -n stackrox --create-namespace \
    stackrox-central-services rhacs/central-services \
    --set scannerV4.disable=false \
    -f <path_to_values_public.yaml> -f <path_to_values_private.yaml>
----
+
.Example output
[source,terminal]
----
Central Services Configuration Summary:

    Stackrox Version:                            4.7.1
    Kubernetes Version:                          v1.31.6
    Kubernetes Namespace:                        stackrox
    Helm Release Name:                           stackrox-central-services
    OpenShift Cluster:                           4
    Scanner V4:                                  enabled
    Scanner V4 DB Volume:                        PVC (scanner-v4-db)
----

. Generate a CRS or an init bundle so that Central and the secured cluster can communicate. For more information, see "Generating and applying a cluster registration secret or an init bundle for RHACS on Red Hat OpenShift" or "Generating and applying a cluster registration secret or an init bundle on other platforms".