// Module included in the following assemblies:
//
// * installing/installing_ocp/init-bundle-ocp.adoc

:_mod-docs-content-type: CONCEPT
[id="generate-init-bundle_{context}"]
= Cluster registration secret or init bundle generation methods

[role="_abstract"]
You can generate a cluster registration secret (CRS) or an init bundle to authenticate your secured clusters by using either the {rh-rhacs-first} portal or the `roxctl` CLI. Both methods produce a YAML file that contains secrets. This file is required to establish the secure communication channel between Central and secured clusters and perform the initial secured cluster registration.

{product-title-short} portal:: This web-based method is suitable for interactive generation. You can select your target platform and installation method through the *Platform Configuration* menu.
`roxctl` CLI:: This command-line method is suitable for scripting and automation. It requires the configuration of the `ROX_API_TOKEN` and `ROX_CENTRAL_ADDRESS` environment variables. You can specify the output format for Helm or Operator installations by using specific command flags.

Regardless of the method used, the generated init bundle contains sensitive secrets. You must store the generated YAML file securely. You can reuse a single init bundle to set up more than one secured cluster if the clusters use the same installation method.

[NOTE]
====
You must have the `Admin` user role to generate an init bundle.
====