// Module included in the following assemblies:
//
// * installing/acs-high-level-overview
:_mod-docs-content-type: CONCEPT
[id="installing-rhacs-ocp-steps_{context}"]
= Installation steps for RHACS on OpenShift Container Platform

[id="installing-ocp-operator-steps"]
== Installing {product-title-short} on {osp} by using the {product-title-short} Operator

. On the {osp} cluster, install the {product-title-short} Operator into the `rhacs-operator` project, or namespace.
. On the {osp} cluster that will contain Central, called the central cluster, use the {product-title-short} Operator to install Central services into the `stackrox` project. One central cluster can secure multiple clusters.
. Log in to the {product-title-short} web console from the central cluster, and generate a cluster registration secret (CRS) or an init bundle and download it. The CRS or the init bundle is then installed on the cluster that you want to secure, called the secured cluster. The CRS or the init bundle contains the cryptographic artifacts that {product-title-short} uses to establish trusted connections between Central and secured clusters. 
+
[NOTE]
====
Init bundles are still supported, but using a CRS is the preferred method for securing your cluster. 
====
. For the secured cluster:
.. Install the {product-title-short} Operator into the `rhacs-operator` namespace.
.. Apply the CRS or the init bundle that you generated in {product-title-short} to the secured cluster by performing one of these steps:
* Use the {ocp} web console to import the YAML file of the CRS or the init bundle that you generated. Make sure you are in the `stackrox` namespace.
* Use the OpenShift CLI to perform one of the following actions:
** If you generated a CRS, in the terminal window, run the `oc create -f <file_name.yaml> -n <stackrox>` command, specifying the path to the downloaded CRS.
** If you generated an init bundle, in the terminal window, run the `oc create -f <init_bundle.yaml> -n <stackrox>` command, specifying the path to the downloaded YAML file of the init bundle.
.. On the secured cluster, use the {product-title-short} Operator to install Secured Cluster services into the `stackrox` namespace. When creating these services, be sure to enter the address of Central in the *Central Endpoint* field so that the secured cluster can communicate with Central.

[id="installing-ocp-helm-steps"]
== Installing {product-title-short} on {osp} by using Helm charts

. Add the {product-title-short} Helm charts repository.
. Install the `central-services` Helm chart on the {osp} cluster that will contain Central, called the central cluster.
. Log in to the {product-title-short} web console on the Central cluster and generate a CRS or an init bundle.
. For each cluster that you want to secure, log in to the secured cluster and use the `helm install` command to install the `secured-cluster-services` Helm chart, specifying the path to the CRS or the init bundle that you generated.

[id="installing-ocp-roxctl-steps"]
== Installing {product-title-short} on {osp} by using the `roxctl` CLI

This installation method is also called the _manifest installation method_.

. Install the `roxctl` CLI.
. On the {osp} cluster that will contain Central, perform these steps:
.. In the terminal window, run the interactive install command by using the `roxctl` CLI.
.. Run the setup shell script.
.. In the terminal window, create the Central resources by using the `oc create` command.
. Perform one of the following actions:
* In the {product-title-short} web console, create and download the sensor YAML file and keys.
* On the secured cluster, use the `roxctl sensor generate openshift` command.
. On the secured cluster, run the sensor installation script.
