// Module included in the following assemblies:
//
// * installing/acs-high-level-overview.adoc
:_mod-docs-content-type: CONCEPT
[id="installation-secrets-auth_{context}"]
= Setting up authentication between Central and secured clusters

[role="_abstract"]
When you install {product-title} ({product-title-short}), you must generate a component that is used between Central and the secured clusters to set up secure communication. Central, also called the Central instance in {rh-rhacscs-first}, is the specific service that provides the ACS Console, handles all API interactions, and manages data storage and image scanning. The user interface is called the {product-title-short} portal for {product-title-short} and is called the ACS Console for {product-title-managed-short}.

The original component used to authenticate when establishing the connection between Central and secured clusters is called an init bundle. A later component, called a cluster registration secret (CRS), provides a more secure mechanism to set up this communication. You generate an init bundle or a CRS in the cluster where Central is located, and then you install it onto the secured clusters.

An init bundle is a YAML file that contains security secrets that allow a new Kubernetes cluster to connect securely to Central. This file is used to create the specific Kubernetes secrets of `sensor-tls`, `collector-tls`, and `admission-control-tls`. These services contain certificates and private keys required for mutual TLS (mTLS) authentication. The certificates inside an init bundle are valid for one year by default. If they expire, the secured cluster will disconnect, and you must generate and apply a new bundle.

A single init bundle can be used to connect multiple different clusters to the same Central instance, although using unique bundles for different groups of clusters can make revoking access easier if credentials are compromised. You can reapply an init bundle to a secured cluster to provide an existing secured cluster with new or updated certificates. 

Beginning with {product-title-short} version 4.7, {product-title-short} provides a more secure alternative to init bundles, called Cluster Registration Secrets (CRSes). Unlike an init bundle, which contains long-lived certificates, a CRS contains a token that the secured cluster uses to request its own certificates. Therefore, you can revoke the CRS immediately after installation without breaking the cluster's connection. Unlike init bundles, you cannot put a new CRS on the cluster and have the secured cluster use this CRS to reestablish the communication with Central. You must generate a new CRS in Central and then reapply the new CRS to the secured cluster and reestablish the secured connection.