// Module included in the following assemblies:
//
// * installing/installing_helm/install-helm-customization.adoc
// * installing/install-ocp-operator.adoc
//
// You must declare the `topic-helm` or `topic-operator` attribute when using this module.
:_module-type: PROCEDURE
[id="roxctl-generate-init-bundle_{context}"]
= Generating an init bundle by using the roxctl CLI

You can create an init bundle with secrets by using the `roxctl` CLI.

.Prerequisites
* You have configured the `ROX_API_TOKEN` and the `ROX_CENTRAL_ADDRESS` environment variables. See xref:../cli/getting-started-cli.html#using-cli_cli-getting-started[Using the roxctl CLI] for more information.

.Procedure

* Run the following command to generate a cluster init bundle containing secrets:
+
ifdef::topic-helm[]
[source,terminal]
----
$ roxctl -e "$ROX_CENTRAL_ADDRESS" \
  central init-bundles generate <cluster_init_bundle_name> \
  --output cluster_init_bundle.yaml
----
endif::[]

ifdef::topic-operator[]
[source,terminal]
----
$ roxctl -e "$ROX_CENTRAL_ADDRESS" \
  central init-bundles generate <cluster_init_bundle_name> \
  --output-secrets cluster_init_bundle.yaml
----
endif::[]

[IMPORTANT]
====
Make sure that you store this bundle securely because it contains secrets.
You can use the same bundle to set up multiple secured clusters.
====
