// Module included in the following assemblies:
//
// * installing/installing_ocp/init-bundle-ocp.adoc

:_mod-docs-content-type: CONCEPT
[id="secured-cluster-authentication-options_{context}"]
= Secured cluster authentication options

[role="_abstract"]
You can use either a cluster registration secret (CRS) or an init bundle during installation of a secured cluster. This allows Central and secured clusters to securely communicate.

Before you set up a secured cluster, you must generate a CRS or an init bundle. The secured cluster then uses the contained secrets for initial authentication with Central. You can generate a CRS or an init bundle by using either the {product-title-short} portal or the `roxctl` CLI. 

You can then apply the CRS or the init bundle by using the {ocp} web console or by using the `oc` or `kubectl` CLI. If you install {product-title-short} by using Helm, you provide the CRS or the init bundle when you run the `helm install` command.

[NOTE]
====
You must have the `Admin` user role to generate a CRS or an init bundle.
====