:_mod-docs-content-type: ASSEMBLY
[id="init-bundle-cloud-ocp-generate"]
= Generating a cluster registration secret or an init bundle for secured clusters
include::modules/common-attributes.adoc[]
:context: init-bundle-cloud-ocp-generate

toc::[]

[role="_abstract"]

Before you set up a secured cluster, you must generate a cluster registration secret (CRS) or an init bundle that contains secrets for initial authentication with the Central instance, also called Central. Generate a CRS or an init bundle by using either the {product-title-short} portal or the `roxctl` CLI, and then apply the CRS or the init bundle to the secured cluster.

[NOTE]
====
You must have the `Admin` user role to generate a CRS or an init bundle. Init bundles are still supported, but using a CRS is the preferred way to set up a secured cluster.
====

Before you set up a secured cluster, you must generate a CRS or an init bundle. The secured cluster then uses the contained secrets for initial authentication with Central. Central is the specific service that provides the ACS Console, handles all API interactions, and manages data storage and image scanning. Use either the {product-title-short} portal or the `roxctl` CLI to generate a CRS or an init bundle.

You can then apply the CRS or the init bundle by using the {ocp} web console or by using the `oc` or `kubectl` CLI. If you install {product-title-short} by using Helm, you provide the CRS or the init bundle when you run the `helm install` command.

[id="generate-init-bundle-cloud-ocp"]
== Generating a CRS or an init bundle

include::modules/portal-generate-init-bundle.adoc[leveloffset=+2]
include::modules/crs-generate-roxctl.adoc[leveloffset=+2]
include::modules/roxctl-generate-init-bundle.adoc[leveloffset=+2]

[id="next-steps_init-bundle-cloud-ocp-generate"]
== Next steps

* xref:../../cloud_service/installing_cloud_ocp/init-bundle-cloud-ocp-apply.adoc#create-resource-init-bundle_init-bundle-cloud-ocp-apply[Applying a cluster registration secret or an init bundle for secured clusters]