:_mod-docs-content-type: ASSEMBLY
[id="init-bundle-cloud-other-generate"]
= Generating a cluster registration secret or an init bundle for Kubernetes secured clusters
include::modules/common-attributes.adoc[]
:context: init-bundle-cloud-other-generate

toc::[]

[role="_abstract"]

Before you set up a secured cluster, you must generate a cluster registration secret (CRS) or an init bundle. The secured cluster then uses the contained secrets for initial authentication with the Central instance, also called Central. To set up the secured connection between Central and your secured clusters, you can use either a CRS or an init bundle, but using a CRS is the preferred method. 

You can generate a CRS or an init bundle by using either of the following methods:

* In the {product-title-short} portal, go to *Platform Configuration* -> *Clusters* and select *Cluster Registration Secrets* (preferred) or *Init bundles*.
* Use the `roxctl` CLI to generate a CRS or an init bundle by using the following commands:
** `roxctl central crs generate` 
** `roxctl central init-bundles generate` 

After you generate a CRS or an init bundle, you provide the CRS or the init bundle when you run the `helm install` command.

[id="generate-init-bundle-cloud-kube"]
== Generating a CRS or an init bundle

include::modules/portal-generate-init-bundle.adoc[leveloffset=+2]
include::modules/crs-generate-roxctl.adoc[leveloffset=+2]
include::modules/roxctl-generate-init-bundle.adoc[leveloffset=+2]

[id="next-steps_init-bundle-cloud-other-generate"]
== Next steps

* xref:../../cloud_service/installing_cloud_other/init-bundle-cloud-other-apply.adoc#create-resource-init-bundle_init-bundle-cloud-other-apply[Creating resources by using the CRS or the init bundle]